apiVersion: v1
kind: ConfigMap
metadata:
  name: esocial-frontend-config
data:
{{- with .Values.frontend.envs }}    
  PROFILE: "{{ .PROFILE }}"
  KEYCLOAK_AUTH_SERVER_URL: "{{ .KEYCLOAK_AUTH_SERVER_URL }}"
  URL_BACKEND: "{{ .URL_BACKEND }}"
{{- end }}