apiVersion: v1
kind: ConfigMap
metadata:
  name: esocial-gerencial-config
data:
  CONECTORES_DS_URL: "{{ .Values.gerencial.envs.CONECTORES_DS_URL }}"
  CONECTORES_DS_USERNAME: "{{ .Values.gerencial.envs.CONECTORES_DS_USERNAME }}"
  CONECTORES_DS_PASSWORD: "{{ .Values.gerencial.envs.CONECTORES_DS_PASSWORD }}"  
  {{- with .Values.gerencial.envs.CONECTORES_DS_MAX_POOL }}
    CONECTORES_DS_MAX_POOL: "{{ .Values.conectividade.envs.CONECTIVIDADE_DS_MAX_POOL }}"
  {{- end }} 
  {{- with .Values.gerencial.envs.CONECTORES_DS_MIN_POOL }}
    CONECTORES_DS_MIN_POOL: "{{ .Values.gerencial.envs.CONECTORES_DS_MIN_POOL }}"
  {{- end }} 

  GERENCIAL_DS_URL: "{{ .Values.gerencial.envs.GERENCIAL_DS_URL }}"
  GERENCIAL_DS_USERNAME: "{{ .Values.gerencial.envs.GERENCIAL_DS_USERNAME }}"
  GERENCIAL_DS_PASSWORD: "{{ .Values.gerencial.envs.GERENCIAL_DS_PASSWORD }}"
  {{- with .Values.gerencial.envs.GERENCIAL_DS_MAX_POOL }}
    GERENCIAL_DS_MAX_POOL: "{{ .Values.gerencial.envs.GERENCIAL_DS_MAX_POOL }}"
  {{- end }} 
  {{- with  .Values.gerencial.envs.GERENCIAL_DS_MIN_POOL }}
    GERENCIAL_DS_MIN_POOL: "{{  .Values.gerencial.envs.GERENCIAL_DS_MIN_POOL }}"
  {{- end }} 