apiVersion: v1
kind: ConfigMap
metadata:
  name: esocial-gerencial-config
data:
{{- with .Values.gerencial.envs }}
  CONECTORES_DS_URL: "{{ .CONECTORES_DS_URL }}"
  CONECTORES_DS_USERNAME: "{{ .CONECTORES_DS_USERNAME }}"
  CONECTORES_DS_PASSWORD: "{{ .CONECTORES_DS_PASSWORD }}"  
  {{ if .CONECTORES_DS_MAX_POOL }}  
  CONECTORES_DS_MAX_POOL: "{{ .CONECTORES_DS_MAX_POOL }}"  
  {{- end }}
  {{ if .CONECTORES_DS_MIN_POOL }}
  CONECTORES_DS_MIN_POOL: "{{ .CONECTORES_DS_MIN_POOL }}"
  {{- end }}
  GERENCIAL_DS_URL: "{{ .GERENCIAL_DS_URL }}"
  GERENCIAL_DS_USERNAME: "{{ .GERENCIAL_DS_USERNAME }}"
  GERENCIAL_DS_PASSWORD: "{{ .GERENCIAL_DS_PASSWORD }}"
  {{ if .GERENCIAL_DS_MAX_POOL }}  
  GERENCIAL_DS_MAX_POOL: "{{ .GERENCIAL_DS_MAX_POOL }}"  
  {{- end }}
  {{ if .GERENCIAL_DS_MIN_POOL }}
  GERENCIAL_DS_MIN_POOL: "{{ .GERENCIAL_DS_MIN_POOL }}"  
  {{- end }}
  {{ if .MEMORIA }}
  MEMORIA: "{{ .MEMORIA }}"
  {{- end }}
{{- end }}