apiVersion: apps/v1
kind: Deployment
metadata:
  name: esocial-gerencial
  labels:
    app: esocial-gerencial
spec:
  {{- if not .Values.gerencial.autoscaling.enabled }}
  replicas: {{ .Values.gerencial.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: esocial-gerencial
  template:
    metadata:      
      labels:
        app: esocial-gerencial
    spec:
      {{ if .Values.imagePullSecrets.enabled }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      {{- end }}    
      containers:
        - name: esocial-gerencial  
          image: "{{ .Values.gerencial.image.repository }}:{{ .Values.gerencial.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          envFrom:
          - configMapRef: 
              name: esocial-gerencial-config
          - secretRef:
              name: secret-gerencial
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:              
              port: http
            initialDelaySeconds: 240
          readinessProbe:
            tcpSocket:              
              port: http
            initialDelaySeconds: 45
          resources:
            {{- toYaml .Values.gerencial.resources | nindent 12 }}
