apiVersion: v1
kind: Secret
metadata:
  name: secret-gerencial
type: Opaque
data:
  CONECTORES_DS_PASSWORD: {{ .Values.gerencial.envs.CONECTORES_DS_PASSWORD | b64enc }}
  GERENCIAL_DS_PASSWORD: {{ .Values.gerencial.envs.GERENCIAL_DS_PASSWORD | b64enc }}
  