apiVersion: v1
kind: ConfigMap
metadata:
  name: esocial-conectividade-config
data:
{{- with .Values.conectividade.envs }}
  CONECTIVIDADE_DS_URL: "{{ .CONECTIVIDADE_DS_URL }}"
  CONECTIVIDADE_DS_USERNAME: "{{ .CONECTIVIDADE_DS_USERNAME }}"  
{{ if .CONECTIVIDADE_DS_MAX_POOL }}
  CONECTIVIDADE_DS_MAX_POOL: "{{ .CONECTIVIDADE_DS_MAX_POOL }}"
{{- end }}
{{ if .CONECTIVIDADE_DS_MIN_POOL }}
  CONECTIVIDADE_DS_MIN_POOL: "{{ .CONECTIVIDADE_DS_MIN_POOL }}"
{{- end }}
{{ if .MEMORIA }}
  MEMORIA: "{{ .MEMORIA }}"
{{- end }}
{{- end }}