apiVersion: v1
kind: Service
metadata:
  name: esocial-conectividade-service
  labels:
    app: esocial-conectividade
spec:
  type: {{ .Values.conectividade.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: esocial-conectividade
