apiVersion: v1
kind: ConfigMap
metadata:
  name: esocial-backend-config
data:
{{- with .Values.backend.envs }}
  DB_URL: "{{ .DB_URL }}"
  DB_USER: "{{ .DB_USER }}"
  DB_PASS: "{{ .DB_PASS }}"
  GELF_APPENDER: "{{ .GELF_APPENDER }}"
{{ if .DB_MAXIMUM_POOL_SIZE }}
  DB_MAXIMUM_POOL_SIZE: "{{ .DB_MAXIMUM_POOL_SIZE }}"
{{- end }}  
{{- end }}
  