apiVersion: apps/v1
kind: Deployment
metadata:
  name: esocial-backend
  labels:
    app: esocial-backend
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: esocial-backend
  template:
    metadata:      
      labels:
        app: esocial-backend
    spec:
      {{- with .Values.backend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}     
      containers:
        - name: esocial-backend  
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          envFrom:
          - configMapRef: 
              name: esocial-backend-config
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:              
              port: http
            initialDelaySeconds: 240
          readinessProbe:
            tcpSocket:              
              port: http
            initialDelaySeconds: 45
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
