apiVersion: apps/v1
kind: Deployment
metadata:
  name: esocial-gerencial
  labels:
    app: esocial-gerencial
spec:
  {{- if not .Values.gerencial.autoscaling.enabled }}
  replicas: {{ .Values.gerencial.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: esocial-gerencial
  template:
    metadata:      
      labels:
        app: esocial-gerencial
    spec:
      {{- with .Values.gerencial.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}     
      containers:
        - name: esocial-gerencial  
          image: "{{ .Values.gerencial.image.repository }}:{{ .Values.gerencial.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          envFrom:
          - configMapRef: 
              name: esocial-gerencial-config
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.gerencial.resources | nindent 12 }}
