{{- if .Values.gerencial.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: esocial-gerencial-hpa
  labels:
    {{- include "esocial.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: esocial-gerencial
  minReplicas: {{ .Values.gerencial.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.gerencial.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.gerencial.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.gerencial.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.gerencial.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.gerencial.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
